# <center>DATA PREPROCESSING<center>

## Database Columns

- Description
- Date
- Month 
- Year
- City
- State
- Zone
- Casualities
- Number of Casualities
- Equipments used for Attack
- Literacy
- Population of the City
- Number of Incidents
- Growth in GDP
- Inflation Rate

## Import the Necessary Libraries

In [1]:
from bs4 import BeautifulSoup as soup
from urllib.request import Request,urlopen as uReq
import urllib.request
import re
from datetime import datetime
import json
import pandas as pd
import csv

### Snippet for Scraping Data from Webpage

In [2]:
# STATES OF INDIA
State_names = ['Andhra Pradesh','Arunachal Pradesh','Assam','Bihar','Chhattisgarh','Goa','Gujarat','Haryana','Himachal Pradesh','Jharkhand','Karnataka','Kerala','Madhya Pradesh','Maharashtra','Manipur','Meghalaya','Mizoram','Nagaland','Odisha','Punjab','Rajasthan','Sikkim','TamilNadu','Telangana','Tripura','Uttar Pradesh','Uttarakhand','WestBengal']


AndhraPradesh = ['Anantapur','Chittoor','East Godavari','Guntur','Kadapa','Krishna','Kurnool','Prakasam','Nellore','Srikakulam','Visakhapatnam','Vizianagaram','West Godavari']
ArunachalPradesh = ['Changlang','Upper Dibang Valley','East Kameng','East Siang','Lohit','Lower Subansiri','PapumPare','Tawang','Tirap','Upper Siang','Upper Subansiri','West Kameng','West Siang','Anjaw','Lower Dibang Valley','Kurung Kumey']
Assam = ['West Karbi Anglong','Udalguri','Tinsukia','South Salmara-Mankachar','Sonitpur','Sivasagar','Nalbari','Nagaon','Morigaon','Majuli','Lakhimpur','Kokrajhar','Karimganj','Karbi Anglong','Kamrup Metropolitan','Kamrup','Jorhat','Hojai','Hailakandi','Golaghat','Goalpara','Dima Hasao','Dibrugarh','Dhubri','Dhemaji','Darrang','Chirang','Charaideo','Cachar','Bongaigaon','Biswanath','Barpeta','Baksa']
Bihar = ['West Champaran','Vaishali','Siwan','Supaul','Sitamarhi','Saran','Sheikhpura','Sheohar','Samastipur','Saharsa','Rohtas','Purnia','Patna','Nawada','Nalanda','Muzaffarpur','Madhepura','Munger','Madhubani','Lakhisarai','Katihar','Kaimur','Kishanganj','Khagaria','Jehanabad','Jamui','Gopalganj','Gaya','East Champaran','Darbhanga','Buxar','Bhojpur','Bhagalpur','Begusarai','Banka','Aurangabad','Arwal','Araria']
Chattisgarh = ['Raipur','Bilaspur','Durg','Korba','Raigarh','Rajnandgaon','Koriya','Surguja','Balrampur-Ramanujganj','Jashpur','Surajpur','Janjgirâ€“Champa','Mungeli','Kabirdham','Bemetara','Balod','Baloda Bazar-Bhatapara','Gariaband','Mahasamund','Dhamtari','Bijapur','Narayanpur','Kanker','Bastar','Dantewada','Kondagaon','Sukma']
Goa = ['North Goa','South Goa']
Gujarat = ['Ahmedabad','Amreli','Anand','Aravalli','Banaskantha','Bharuch','Bhavnagar','Botad','Chhota-Udepur','Dahod','Dang','Devbhoomi-Dwarka','Gandhinagar','Gir-Somnath','Jamnagar','Junagadh','Kheda','Kutch','Mahisagar','Mehsana','Morbi','Narmada','Navsari','Panchmahal','Patan','Porbandar','Rajkot','Sabarkantha','Surat','Surendranagar','Tapi','Vadodara','Valsad']
Haryana = ['Ambala','Bhiwani','Charkhi-Dadri','Faridabad','Fatehabad','Gurugram','Hissar','Jhajjar','Jind','Kaithal','Karnal','Kurukshetra','Mahendragarh','Nuh','Palwal','Panchkula','Panipat','Rewari','Rohtak','Sirsa','Sonipat','Yamuna-Nagar']
HimachalPradesh = ['Bilaspur','Chamba','Hamirpur','Kangra','Kinnaur','Kullu','Lahaul and Spiti','Mandi','Shimla','Sirmaur','Solan','Una']
Jharkhand = ['Bokaro','Chatra','Deoghar','Dhanbad','Dumka','East-Singhbhum','Garhwa','Giridih','Godda','Gumla','Hazaribag','Jamtara','Khunti','Koderma','Latehar','Lohardaga','Pakur','Palamu','Ramgarh','Ranchi','Sahibganj','Seraikela-Kharsawan','Simdega','West-Singhbhum']
Karnataka = ['Bagalkot','Ballari','Belagavi','Bengaluru-Rural','Bengaluru-Urban','Bidar','Chamarajnagar','Chikkaballapur','Chikkamagaluru','Chitradurga','Dakshina-Kannada','Davanagere','Dharwad','Gadag','Hassan','Haveri','Kalaburagi','Kodagu','Kolar','Koppal','Mandya','Mangaluru','Mysuru','Raichur','Ramanagara','Shivamogga','Tumakuru','Udupi','Uttara-Kannada','Vijayapura','Yadgir']
Kerala = ['Alappuzha','Ernakulam','Idukki','Kannur','Kasaragod','Kollam','Kottayam','Kozhikode','Malappuram','Palakkad','Pathanamthitta','Thrissur','Thiruvananthapuram','Wayanad']
MadhyaPradesh = ['Agar-Malwa','Alirajpur','Anuppur','Ashok-Nagar','Balaghat','Barwani','Betul','Bhind','Bhopal','Burhanpur','Chhatarpur','Chhindwara','Damoh','Datia','Dewas','Dhar','Dindori','Guna','Gwalior','Harda','Hoshangabad','Indore','Jabalpur','Jhabua','Katni','Khandwa(East-Nimar)','Khargone(West-Nimar)','Mandla','Mandsaur','Morena','Narsinghpur','Neemuch','Niwari','Panna','Raisen','Rajgarh','Ratlam','Rewa','Sagar','Satna','Sehore','Seoni','Shahdol','Shajapur','Sheopur','Shivpuri','Sidhi','Singrauli','Tikamgarh','Ujjain','Umaria','Vidisha']
Maharashtra = ['Ahmednagar','Akola','Amravati','Aurangabad','Beed','Bhandara','Buldhana','Chandrapur','Dhule','Gadchiroli','Gondia','Hingoli','Jalgaon','Jalna','Kolhapur','Latur','Mumbai','Mumbai-suburban','Nanded','Nandurbar','Nagpur','Nashik','Osmanabad','Palghar','Parbhani','Pune','Raigad','Ratnagiri','Sangli','Satara','Sindhudurg','Solapur','Thane','Wardha','Washim','Yavatmal']
Manipur = ['Bishnupur','Chandel','Churachandpur','Imphal East','Imphal West','Jiribam','Kakching','Kamjong','Kangpokpi','Noney','Pherzawl','Senapati','Tamenglong','Tengnoupal','Thoubal','Ukhrul']
Meghalaya = ['East Garo Hills','East Khasi Hills','East Jaintia Hills','North Garo Hills','Ri Bhoi','South Garo Hills','South West Garo Hills','South West Khasi Hills','West Jaintia Hills','West Garo Hills','West Khasi Hills']
Mizoram = ['Aizawl','Champhai','Kolasib','Lawngtlai','Lunglei','Mamit','Saiha','Serchhip']
Nagaland = ['Dimapur','Kiphire','Kohima','Longleng','Mokokchung','Mon','Noklak','Peren','Phek','Tuensang','Wokha','Zunheboto']
Odisha = ['Angul','Boudh','Bhadrak','Balangir','Bargarh','Balasore','Cuttack','Debagarh','Dhenkanal','Chhatrapur','Paralakhemundi','Jharsuguda','Panikoili','Jagatsinghpur','Khordha','Kendujhar','Bhawanipatna','Phulbani','Koraput','Kendrapara','Malkangiri','Baripada','Nabarangpur','Nuapada','Nayagarh','Puri','Rayagada','Sambalpur','Subarnapur','Sundargarh']
Punjab =['Amritsar','Barnala','Bathinda','Firozpur','Faridkot','Fatehgarh-Sahib','Fazilka','Gurdaspur','Hoshiarpur','Jalandhar','Kapurthala','Ludhiana','Mansa','Moga','Sri-Muktsar-Sahib','Pathankot','Patiala','Rupnagar','Sahibzada-Ajit-Singh-Nagar','Sangrur','Shahid-Bhagat-Singh-Nagar','Tarn-Taran']
Rajasthan = ['Ajmer','Alwar','Bikaner','Barmer','Banswara','Bharatpur','Baran','Bundi','Bhilwara','Churu','Chittorgarh','Dausa','Dholpur','Dungarpur','Ganganagar','Hanumangarh','Jhunjhunu','Jalore','Jodhpur','Jaipur','Jaisalmer','Jhalawar','Karauli','Kota','Nagaur','Pali','Pratapgarh','Rajsamand','Sikar','Sawai Madhopur','Sirohi','Tonk','Udaipur']
Sikkim = ['East Sikkim','North Sikkim','South Sikkim','West Sikkim']
TamilNadu=['Ariyalur','Chengalpattu','Chennai','Coimbatore','Cuddalore','Dharmapuri','Dindigul','Erode','Kallakurichi','Kanchipuram','Kanyakumari','Karur','Krishnagiri','Madurai','Nagapattinam','Nilgiris','Namakkal','Perambalur','Pudukkottai','Ramanathapuram','Ranipet','Salem','Sivaganga','Tenkasi','Tirupur','Tiruchirappalli','Theni','Tirunelveli','Thanjavur','Thoothukudi','Tirupattur','Tiruvallur','Tiruvarur','Tiruvannamalai','Vellore','Viluppuram','Virudhunagar']
Telangana = ['Adilabad','Komaram-Bheem','Bhadradri-Kothagudem','Hyderabad','Jagtial','Jangaon','Jayashankar-Bhupalpally','Jogulamba-Gadwal','Kamareddy','Karimnagar','Khammam','Mahabubabad','Mahbubnagar','Mancherial','Medak','Medchal-Malkajgiri','Mulugu','Nalgonda','Narayanpet','Nagarkurnool','Nirmal','Nizamabad','Peddapalli','Rajanna-Sircilla','Ranga-Reddy','Sangareddy','Siddipet','Suryapet','Vikarabad','Wanaparthy','Warangal-Urban','Warangal-Rural','Yadadri-Bhuvanagiri']
Tripura = ['Dhalai','Gomati','Khowai','North Tripura','Sepahijala','South Tripura','Unokoti','West Tripura']
UttarPradesh = ['Agra','Aligarh','Allahabad','Ambedkar-Nagar','Amethi','Amroha','Auraiya','Azamgarh','Bagpat','Bahraich','Ballia','Balrampur','Banda','Barabanki','Bareilly','Basti','Bhadohi','Bijnor','Budaun','Bulandshahr','Chandauli','Chitrakoot','Deoria','Etah','Etawah','Faizabad','Farrukhabad','Fatehpur','Firozabad','Gautam-Buddh-Nagar','Ghaziabad','Ghazipur','Gonda','Gorakhpur','Hamirpur','Hapur','Hardoi','Hathras','Jalaun','Jaunpur','Jhansi','Kannauj','Kanpur-Dehat','Kanpur-Nagar','Kasganj','Kaushambi','Kushinagar','Lakhimpur-Kheri','Lalitpur','Lucknow','Maharajganj','Mahoba','Mainpuri','Mathura','Mau','Meerut','Mirzapur','Moradabad','Muzaffarnagar','Pilibhit','Pratapgarh','Raebareli','Rampur','Saharanpur','Sambhal','Sant-Kabir-Nagar','Shahjahanpur','Shamli','Shravasti','Siddharth Nagar','Sitapur','Sonbhadra','Sultanpur','Unnao','Varanasi']
Uttarakhand = ['Almora','Bageshwar','Chamoli','Champawat','Dehradun','Haridwar','Nainital','Pauri-Garhwal','Pithoragarh','Rudraprayag','Tehri-Garhwal','Udham-Singh-Nagar','Uttarkashi']
WestBengal = ['Alipurduar','Bankura','Paschim Bardhaman','Purba Bardhaman','Birbhum','Cooch Behar','Dakshin Dinajpur','Darjeeling','Hooghly','Howrah','Jalpaiguri','Jhargram','Kalimpong','Kolkata','Maldah','Murshidabad','Nadia','North-24-Parganas','Paschim-Medinipur','Purba-Medinipur','Purulia','South-24-Parganas','Uttar-Dinajpur']


# UNION TERRORITIES
UnionTerritory_names = ['Andaman and Nicobar Islands','Chandigarh','Dadra and Nagar Haveli','Daman and Diu','Delhi','Jammu and Kashmir','Kashmir','Ladakh','Lakshadweep','Puducherry']


AndamanandNicobarIslands = ['Nicobar','North and Middle Andaman','South Andaman']
Chandigarh = ['Chandigarh']
DadraandNagarHaveli = ['Dadra and Nagar Haveli']
DamanandDiu = ['Daman','Diu']
Delhi = ['Central Delhi','East Delhi','New Delhi','North Delhi','North East Delhi','North West Delhi','Shahdara','South Delhi','South East Delhi','South West Delhi','West Delhi']
JammuandKashmir = ['Anantnag','Bandipora','Baramulla','Badgam','Doda','Ganderbal','Jammu','Kathua','Kishtwar','Kulgam','Kupwara','Poonch','Pulwama','Rajouri','Ramban','Reasi','Samba','Shupiyan','Srinagar','Udhampur']
Ladakh = ['Kargil','Leh']
Lakshadweep = ['Lakshadweep']
Puducherry = ['Karaikal','MahÃ©','Pondicherry','Yanam']


# LIST OF STATES - LIST OF LIST
state_lists = [AndhraPradesh,ArunachalPradesh,Assam,Bihar,Chattisgarh,Goa,Gujarat,Haryana,HimachalPradesh,Jharkhand,Karnataka,Kerala,MadhyaPradesh,Maharashtra,Manipur,Meghalaya,Mizoram,Nagaland,Odisha,Punjab,Rajasthan,Sikkim,TamilNadu,Telangana,Tripura,UttarPradesh,Uttarakhand,WestBengal]


# LIST OF STATES - LIST OF LIST
unionterritory_lists = [AndamanandNicobarIslands,Chandigarh,DadraandNagarHaveli,DamanandDiu,Delhi,JammuandKashmir,Ladakh,Lakshadweep,Puducherry]

# MONTHS
Month_names = ['-','JANUARY','FEBRUARY','MARCH','APRIL','MAY','JUNE','JULY','AUGUST','SEPTEMBER','OCTOBER','NOVEMBER','DECEMBER']

In [3]:
# LIST OF ALL UNION TERRITORIES AND STATES

State_UnionTerritory_names = State_names + UnionTerritory_names

# SORTING THE LIST OF STATES

for i in range(len(State_names)):
    state_lists[i].sort()

# SORTING THE LIST OF UNION TERRITORIES

for i in range(len(UnionTerritory_names)):
    unionterritory_lists[i-1].sort()
    
# CREATING A DICTIONARY 
d1 = {}
for i in range(len(State_names)):
    d1.setdefault(State_names[i],state_lists[i])

d2 = {}
for i in range(len(UnionTerritory_names)):
    d2.setdefault(UnionTerritory_names[i-1],unionterritory_lists[i-1])
# DICTIONARY OF ZONES
zone = {'North':['Chandigarh','Delhi','Haryana','Himachal Pradesh','Jammu and Kashmir','Kashmir','Ladakh','Punjab','Rajasthan'],
        'North East':['Assam','Arunachal Pradesh','Manipur','Meghalaya','Mizoram','Nagaland','Sikkim','Tripura'],
        'Central':['Chattisgarh','Madhya Pradesh','Uttarakhand','Uttar Pradesh'],
        'East':['Bihar','Jharkhand','Odisha','West Bengal'],
        'West':['Dadra and Nagar Haveli','Daman and Diu',' Goa',' Gujarat','Maharashtra'],
        'South':['Andaman and Nicobar Islands','Andhra Pradesh','Karnataka','Kerala','Lakshadweep','Puducherry','Tamil Nadu','Telangana']}

# LIST OF EQUIPMENTS
equipments = ['IED','BOMBS','BOMB','GRENADE','EXPLOSIVES','PISTOL','STONES','STONE','GUNS','ACID','RIFLES','RIFLE']

# DICT OF TERRORIST ORGANISATION NAMES
terrorist_group = {'Al-Badr':['Al-Badr'],'All Tripura Tiger Force':['All Tripura Tiger Force'],'Al-Qaeda':['Al-Qaeda'],'Al-Umar-Mujahideen':['Al-Umar-Mujahideen'],'Babbar Khalsa International':['Babbar Khalsa International'],
                   'Deendar Anjuman':['Deendar Anjuman'],'Dukhtaran-E-Millat':['Dukhtaran-E-Millat','DEM'],'Garo National Liberation Army':['Garo National Liberation Army','GNLA'],
                   'Harkat-Ul-Mujahideen':['Harkat-Ul-Mujahideen'],'Hizb-Ul-Mujahideen':['Hizb-Ul-Mujahideen'],'Indian Mujahideen':['Indian Mujahideen'],'International Sikh Youth Federation':['International Sikh Youth Federation'],
                   'ISIS':['Islamic State of Iraq','ISIS'],'Jaish-E-Mohammed':['Jaish-E-Mohammed'],'Jamiat-ul-Mujahideen':['Jamiat-ul-Mujahideen'],'Jammu and Kashmir Islamic Front':['Jammu and Kashmir Islamic Front'],
                   'Kamatapur Liberation Organization':['Kamatapur Liberation Organization'],'Kanglei Yawol Kanna Lup':['Kanglei Yawol Kanna Lup','KYKL'],'Kangleipak Communist Party':['Kangleipak Communist Party','KCP'],
                   'Lashkar-E-Taiba':['Lashkar-E-Taiba'],'Liberation Tigers of Tamil Eelam':['Liberation Tigers of Tamil Eelam','LTTE'],'Manipur Peopleâ€™s Liberation Front':['Manipur Peopleâ€™s Liberation Front','MPLF'],
                   'Maoist Communist Centre':['Maoist Communist Centre','MCC','Maoist'],'Tehreek-ul-Mujahideen':['Tehreek-ul-Mujahideen','TuM'],'Naxalite Groups':['Naxalites']}

#### 1] Description :
- Collecting the headline as it is from the webpage
- Scraping the data from <H1 & H2> HTML tags respectively

In [4]:
def get_description(h1,h2):
    h = h1 + '.' + h2                                
    comma = ','
    no_punct = ""
    for char in h:
        if char not in comma:
            no_punct = no_punct + char
    return (no_punct)

#### Removing Punctuation Marks

In [5]:
def no_punctuations(description):
    punctuations = '''!â€™()-[]{};:'"\,<>./?@#$%^&*_~'''
    no_punct = ""
    for char in description:
        if char not in punctuations:
            no_punct = no_punct + char
    des = no_punct.split()
    return (des)

#### 2] Date :
- Using Regular Expresessions for String Matching
- Using the **OR** condition for selecting the date from all the mentioned formats below

In [6]:
def get_date(div,page_soup):
    for i in div:
        d1 = re.findall(r"((January|February|March|April|May|June|July|August|September|October|November|December) [\d]{1,2}, [\d]{4})",i.text)
        d2 = re.findall(r"((JANUARY|FEBRUARY|MARCH|APRIL|MAY|JUNE|JULY|AUGUST|SEPTEMBER|OCTOBER|NOVEMBER|DECEMBER) [\d]{1,2}, [\d]{4})",i.text)
        d3 = re.findall(r"([\d]{1,2} (January|February|March|April|May|June|July|August|September|October|November|December) [\d]{4})",i.text)
        d4 = re.findall(r"([\d]{1,2} (January|February|March|April|May|June|July|August|September|October|November|December), [\d]{4})",i.text)
        d5 = re.findall(r"((Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec). [\d]{1,2}, [\d]{4})",i.text)
        d6 = re.findall(r"((JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC). [\d]{1,2}, [\d]{4})",i.text)
        d7 = re.findall(r"((Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec) [\d]{1,2}, [\d]{4})",i.text)
        d8 = re.findall(r"( (January|February|March|April|May|June|July|August|September|October|November|December)  [\d]{1,2}, [\d]{4})",i.text)
        d9 = re.findall(r"((Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday), [\d]{1,2} (Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec) [\d]{4})",i.text)
        date = d1 or d2 or d3 or d4 or d5 or d6 or d7 or d8 or d9 
        if (date == (d1)):
            DATE = date[0][0]
            DATE = str(DATE)
            date = datetime.strptime(DATE,'%B %d, %Y')                #MONTH DD, YYYY            
            return(date)
        elif (date == (d2)):
            DATE = date[0][0]
            DATE = str(DATE)
            date = datetime.strptime(DATE,'%B %d, %Y')                #MONTH DD, YYYY   
            return(date)
        elif (date == (d3)):
            DATE = date[0][0]
            DATE = str(DATE)
            date = datetime.strptime(DATE,'%d %B %Y')                 #MONTH DD YYYY
            return(date)
        elif (date == (d4)):
            DATE = date[0][0]
            DATE = str(DATE)
            date = datetime.strptime(DATE,'%d %B, %Y')                #MONTH DD, YYYY
            return(date)
        elif (date == (d5)):
            DATE = date[0][0]
            DATE = str(DATE)
            date = datetime.strptime(DATE,'%b. %d, %Y')               #MONTH. DD, YYYY
            return(date)
        elif (date == (d6)):
            DATE = date[0][0]
            DATE = str(DATE)
            date = datetime.strptime(DATE,'%b. %d, %Y')               #MONTH. DD, YYYY
            return(date)
        elif (date == (d7)):
            DATE = date[0][0]
            DATE = str(DATE)
            date = datetime.strptime(DATE,'%b %d, %Y')                #MONTH DD, YYYY
            return(date)
        elif (date == (d8)):
            DATE = date[0][0]
            DATE = str(DATE)
            date = datetime.strptime(DATE,' %B %d, %Y')               # MONTH DD, YYYY
            return(date)
        elif (date == (d9)):
            DATE = date[0][0]
            DATE = str(DATE)
            date = datetime.strptime(DATE,'%A, %d %b %Y')             #DAY, MONTH DD, YYYY

#### 3] Month :
- Using the month method from the datetime datatype

In [7]:
def get_month(date):
    month = date.month
    return(Month_names[month])

#### 4] Year :
- Using the year method from the datetime datatype

In [8]:
def get_year(date):
    year = date.year
    return(str(year))

#### 5 & 6] City & State / Union Territory :
- Scraping City & State / Union Territory from the headline of the webpage

In [9]:
def get_city_and_state(description):
    description = no_punctuations(description)
    try:
        c,s = city_state(description) or city_ut(description) 
        return(c,s)
    except TypeError as e:                                      # EXCEPTION HANDLING USED WHEN HEADLINE DOES NOT HAVE CITY NAME 
        c = '---'
        s = get_state_ut(description)
        return(c,s)


# FUNCTION USED TO OBTAIN THE STATE OR UNION TERRITORY IN THE ABSENCE OF CITY NAME
def get_state_ut(description):
    for i in State_UnionTerritory_names:                        # STRING MATCHING
        for x in description:
            if(i == x):
                return(i)
            else:
                pass
    return('---')


# FUNCTION USED TO OBTAIN CITY AND STATE NAME
def city_state(description):
    for key,value in d1.items():                              # USING DICTIONARY TO GET THE CITY AND STATE
        for i in description:
            for y in range(len(d1[key])):                     # STATE NAME IS KEY AND CITY NAMES ARE THE LIST OF VALUES
                if(d1[key][y] == i):
                    return(i,key)

# FUNCTION USED TO OBTAIN CITY AND UNION TERRRITORY NAME
def city_ut(description):
    for key,value in d2.items():                              # USING DICTIONARY TO GET THE CITY AND UNION TERRITORY
        for i in description:
            for y in range(len(d2[key])):                     # UNION TERRITORY NAME IS KEY AND CITY NAMES ARE THE LIST OF VALUES
                  if(d2[key][y] == i):
                        return(i,key)

#### 7] Zone :

In [10]:
def get_zone(state):
    for key,value in zone.items():                          # USING DICTIONARY TO GET ZONES OF THE RESPECTIVE STATES AND UNION TERRITORIES
        for y in range(len(zone[key])):
            if(zone[key][y] == state):                      # ZONE NAME IS THE KEY AND STATE NAMES ARE THE LIST OF VALUES
                return(key)
            else:
                pass
    return('---')

#### 8 & 9] Number of Casualities :
- Function used to acquire the number of Casualities & if their are casualities from the headline

In [11]:
def get_casualities(description): 
    words = ['jawans','soldiers','people','person','martyred','martyrs','dead','injured','kills','killed','hurt']
    num = {'1':['One','one'],'2':['Two','two'],'3':['Three','three'],'4':['Four','four'],'5':['Five','five'],'6':['Six','six'],'7':['Seven','seven'],'8':['Eight','eight'],'9':['Nine','nine'],'10':['Ten','ten'],'12':['Dozen','dozen']}
    des = description.split()
    for word in words:
        for d in des:
            if (word == d):
                try:
                    number = re.findall(r"\d+",description)           # USING REGULAR EXPRESSIONS FOR FINDING THE NUMBER OF CASUALTIES
                    return('Yes',number[0])                           # IN NUMERICAL FORMAT
                except IndexError:
                    for key,value in num.items():                     # USING DICTIONARY FOR MACTHING THE NUMBER OF CASUALTIES
                        for j in des:                                 # IN TEXT FORMAT
                            for i in range(2):
                                if (j == num[key][i]):
                                    return('Yes',key)
            else:
                pass

#### 10] Equipments used for Attack :
- Function used to obtain equipments used for attack

In [12]:
def get_equip(description):
    description = description.upper()
    description = no_punctuations(description)     
    for i in description:
        for j in range(len(equipments)):                          #STRING MATCHING   
            if (equipments[j] == i):
                return(i)
            else:
                pass
    return('---')

#### 11] Literacy :
- BEAUTIFUL SOUP library used to scrape the [Wikipedia website](https://en.wikipedia.org/wiki/List_of_Indian_states_and_union_territories_by_literacy_rate) data for literacy

In [13]:
z = r'https://en.wikipedia.org/wiki/List_of_Indian_states_and_union_territories_by_literacy_rate'
response = uReq(z)
page_soup = soup(response,'html.parser')
literacy_state = []                                                          # LIST FOR NAMES OF STATE 
literacy = []                                                                # LIST FOR STORING THE LITERACY DATA
literacy_table = page_soup.findAll('table',{'class':'wikitable sortable'})
literacy_rows = literacy_table[0].findAll('tr')
for i in range(len(literacy_rows)-1):
    literacy_data = literacy_rows[i+1].findAll('td')
    literacy_state.append(literacy_data[1].text)
    literacy.append(literacy_data[2].text)

# STORING THE DATA INTO A CSV FILE FOR AVOIDING REPETITIONS OF THIS PROCESS
df2 = pd.DataFrame()
df2['State Name'] = literacy_state
df2['Literacy'] = literacy
df2.to_csv('LITERACY.csv')

In [14]:
# READING THE CSV FILE IN WHICH LITERACY DATA IS STORED
df2 = pd.read_csv('LITERACY.csv')
del df2['Unnamed: 0']
df2.head()

    State Name  Literacy
0       Kerala     93.91
1  Lakshwadeep     92.28
2      Mizoram     91.58
3      Tripura  87.75[a]
4          Goa     87.40

- Function used to get the literacy of each state from the above scraped data
- Special case of **Kashmir** as it was not mentioned on the website

In [15]:
def get_literacy(state):
    if (state == 'Kashmir'):
        return(df2.iloc[29,1])
    else:
        for i in range(len(df2.index)):
            if(df2.iloc[i,0] == state):
                return(df2.iloc[i,1])
            else:
                pass
        return('DATA NOT AVAILABLE')

#### 12] Population of the States / Union Territory :
- [Wikipedia Website](https://en.wikipedia.org/wiki/List_of_districts_in_India)

In [16]:
website_url = r'https://en.wikipedia.org/wiki/List_of_districts_in_India'
response = uReq(website_url)
page_soup = soup(response,'html.parser')
city_name = []                                                            # LIST OF CITY NAMES
population = []                                                           # LIST OF POPULATION
all_tables = []                                                           # LIST OF ALL THE TABLES
all_tables = page_soup.findAll('table',{'class':'wikitable sortable'})
for at in range(len(all_tables)-1):
    table_rows = all_tables[at+1].findAll('tr')
    for tr in range(len(table_rows)-1):
        table_data = table_rows[tr+1].findAll('td')   # TABLE DATA HAS 7 COLUMNS. WE NEED THE DATA STORED IN 3 AND 5 COLUMN
        city_name.append(table_data[2].text)
        population.append(table_data[4].text)

In [17]:
# ANOTHER FUNCTION USED FOR COLLECTING THE POPULATION DATA 
for i in range(37,38):
    at_row = all_tables[i].findAll('tr')
    for i in range(len(at_row)):
        at_data = at_row[i+1].findAll('td')
        city_name.append(at_data[2].text)
        population.append(at_data[4].text)
        
# STORING THE DATA INTO A CSV FILE FOR AVOIDING REPETITIONS OF THIS PROCESS
df = pd.DataFrame()
df['CITY'] = city_name
df['POPULATION'] = population
df.to_csv('CITY_POP.csv')

In [19]:
df = pd.read_csv('CITY_POP.csv')
del df['Unnamed: 0']
for i in range(len(df.index)):
    df.iloc[i,1] = df.iloc[i,1].replace(',','')
df.head()

            CITY POPULATION
0      Anantapur    4083315
1       Chittoor    4170468
2  East Godavari    5151549
3         Guntur    4889230
4         Kadapa    2884524

In [21]:
# FINAL FUNCTION
def get_pop(city):
    for i in range(len(df.index)):
        if (df.iloc[i,0] == city):
            return(df.iloc[i,1])
        else:
            pass
    return('DATA NOT AVAILABLE')

#### 13] Number of Incidents :
- [Wikipedia Webiste](https://en.wikipedia.org/wiki/List_of_terrorist_incidents_in_India)
- Get the number of incidents from respective year

In [22]:
z = pd.read_html('https://en.wikipedia.org/wiki/List_of_terrorist_incidents_in_India')
t1 = z[1]
t1 = t1.drop(columns = [2,3])

df3 = pd.DataFrame()
df3['Year'] = t1[0]
df3['Number of Incidents'] = t1[1]
df3.to_csv('NUMBER_OF_INCIDENTS.csv')

In [25]:
# STORING THE DATA INTO A CSV FILE FOR AVOIDING REPETITIONS OF THIS PROCESS
df3 = pd.read_csv('NUMBER_OF_INCIDENTS.csv')
del df3['Unnamed: 0']
df3.head()

   Year Number of Incidents
0  Year  Number ofincidents
1  2018                 748
2  2017                1000
3  2016                1025
4  2015                 884

In [27]:
def get_no_incidents(year):
    for i in range(len(df3.index)):
        if (df3.iloc[i,0] == year):
            return(df3.iloc[i,1])
        else:
            pass
    return('DATA NOT AVAILABLE')

#### 14] GDP : 
- Obtaining the GDP of each state by scraping data from [Wikipedia Website]('https://en.wikipedia.org/wiki/Economy_of_India')

In [28]:
w = pd.read_html('https://en.wikipedia.org/wiki/Economy_of_India')
t3 = w[1]
t3 = t3.drop(columns = [1,2,3,6])

# STORING THE DATA INTO A CSV FILE FOR AVOIDING REPETITIONS OF THIS PROCESS
df4 = pd.DataFrame()
df4['Year'] = t3[0]
df4['GDP GROWTH'] = t3[4]
df4['INFLATION RATE'] = t3[5]
df4.to_csv('GDP_INFLATION.csv')

In [29]:
df4 = pd.read_csv('GDP_INFLATION.csv')
del df4['Unnamed: 0']
df4.head()

   Year        GDP GROWTH              INFLATION RATE
0  Year  GDP growth(real)  Inflation rate(in Percent)
1  1980             5.3Â %                      11.3Â %
2  1981             6.0Â %                      12.7Â %
3  1982             3.5Â %                       7.7Â %
4  1983             7.3Â %                      12.6Â %

In [31]:
def get_gdp_growth(year):
    for i in range(len(df4.index)):
        if(df4.iloc[i,0] == year):
            a = df4.iloc[i,1]
            a = a.replace('\xa0%','%')
            return(a)
        else:
            pass
    return('DATA NOT AVAILABLE')

#### 15] Inflation :

In [32]:
#OBTAINING THE INFLATION RATE OF EACH STATE
def get_inflation(year):
    for i in range(len(df4.index)):
        if(df4.iloc[i,0] == year):
            a = df4.iloc[i,2]
            a = a.replace('\xa0%','%')
            return(str(a))
        else:
            pass
    return('DATA NOT AVAILABLE')

#### 16] Terrorist Organisation :
- Obtaining the Terrorist Organisation Name

In [42]:
def get_terrorist_group(description):
    des = description.split()
    for key,value in terrorist_group.items():
        for j in des:
            for i in range(len(terrorist_group[key])):
                if (j == terrorist_group[key][i]):
                    return(key)
                else:
                    pass
    return('DATA NOT AVAILABLE')

## <center>HTML SCRAPER</center>
- Single function which consists of all the above functions to extract information from webpages & storing everything inside a csv file

In [52]:
def html_scraper(x):
    
    DESCRIPTION = [];DATE = [];MONTH = [];YEAR = [];CITY = [];STATE = [];ZONE = [];CASUALITIES = [];NUMBER_OF_CASUALITIES = [];
    EQUIPMENTS = [];LITERACY = [];POPULATION = [];NUMBER_OF_INCIDENTS = [];GROWTH_IN_GDP = [];INFLATION = [];TERRORIST_GROUP = [];
    
    response = uReq(x)
    page_soup = soup(response,'html.parser')
    h1 = page_soup.h1.text
    try:
        h2 = page_soup.h2.text
    except AttributeError as e:
        h2 = '---'
    
    description = get_description(h1,h2)                                            # PARAMETER - 1
    DESCRIPTION.append(description)
    div = page_soup.findAll('div')
    
    date = get_date(div,page_soup)    
    
    month = get_month(date)                                                         # PARAMETER - 2
    MONTH.append(month)
    
    year = get_year(date)                                                           # PARAMETER - 3
    YEAR.append(year)
    
    date = str(date)                                                                # PARAMETER - 4
    DATE.append(date)
    
    (city,state) = get_city_and_state(description)                                  # PARAMETER - 5 & 6
    CITY.append(city)
    STATE.append(state)
    
    zone = get_zone(state)                                                          # PARAMETER - 7
    ZONE.append(zone)
    
    equipments = get_equip(description)                                             # PARAMETER - 8
    EQUIPMENTS.append(equipments)
    
    literacy = get_literacy(state)                                                  # PARAMETER - 9
    LITERACY.append(literacy)
    
    population = get_pop(city)                                                      # PARAMETER - 10
    POPULATION.append(population)
    
    incidents = get_no_incidents(year)                                              # PARAMETER - 11
    NUMBER_OF_INCIDENTS.append(incidents)
    
    GDP = get_gdp_growth(year)                                                      # PARAMETER - 12
    GROWTH_IN_GDP.append(GDP)
    
    inflation = get_inflation(year)                                                 # PARAMETER - 13
    INFLATION.append(inflation)
    
    try:
        
        (casualities,number) = get_casualities(description)                             # PARAMETER - 14 & 15
        CASUALITIES.append(casualities)
        NUMBER_OF_CASUALITIES.append(number)
    except TypeError as e:
        
        CASUALITIES.append('No')
        NUMBER_OF_CASUALITIES.append('0')
    
    terrorist_group = get_terrorist_group(description)
    TERRORIST_GROUP.append(terrorist_group)                                         # PARAMETER - 16
    
    database = pd.DataFrame(columns = ['DESCRIPTION','DATE','MONTH','YEAR','CITY','STATE','ZONE','CASUALTIES','NUMBER OF CASUALTIES','EQUIPMENTS','LITERACY','POPULATION','NUMBER OF INCIDENTS','GROWTH IN GDP','INFLATION','TERRORIST GROUP'])
    database['DESCRIPTION'] = DESCRIPTION;database['DATE'] = DATE;database['MONTH'] = MONTH;database['YEAR'] = YEAR
    database['CITY'] = CITY;database['STATE'] = STATE;database['ZONE'] = ZONE;database['CASUALTIES'] = CASUALITIES
    database['NUMBER OF CASUALTIES'] = NUMBER_OF_CASUALITIES;database['EQUIPMENTS'] = EQUIPMENTS;database['LITERACY'] = LITERACY
    database['POPULATION'] = POPULATION;database['NUMBER OF INCIDENTS'] = NUMBER_OF_INCIDENTS;database['GROWTH IN GDP'] = GROWTH_IN_GDP
    database['INFLATION'] = INFLATION;database['TERRORIST GROUP'] = TERRORIST_GROUP
    
    return (database)

# <center>DEMONSTRATION</center>

In [62]:
link_1 = 'https://www.indiatoday.in/india/story/ied-blast-pulwama-army-convoy-attacked-1550656-2019-06-17'
link_2 = 'https://www.indiatoday.in/science/story/isro-chief-sivan-rejects-nasa-claim-on-locating-vikram-lander-chandrayaan-2-1624919-2019-12-04'

In [63]:
df1 = html_scraper(link_1)
df2 = html_scraper(link_2)
database = pd.concat([df1,df2])

In [66]:
print(database.head())
database.to_csv('DEMO.csv')

,DESCRIPTION,DATE,MONTH,YEAR,CITY,STATE,ZONE,CASUALTIES,NUMBER OF CASUALTIES,EQUIPMENTS,LITERACY,POPULATION,NUMBER OF INCIDENTS,GROWTH IN GDP,INFLATION,TERRORIST GROUP
0,9 jawans injured in IED blast in Pulwama.An ar...,2019-06-17 00:00:00,JUNE,2019,Pulwama,Jammu and Kashmir,North,Yes,9,IED,68.74,570060,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE
1,Our orbiter located Vikram lander first: Isro ...,2019-12-04 00:00:00,DECEMBER,2019,---,---,---,No,0,---,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE

# <center>Database Used For Further Process</center>
- 100 webpages were parsed through the above the **html_scraper()** function

In [27]:
complete_dataset = pd.read_csv('DATABASE.csv')
del complete_dataset['Unnamed: 0']
complete_dataset

,DESCRIPTION,DATE,MONTH,YEAR,CITY,STATE,ZONE,CASUALITIES,NUMBER OF CASUALITIES,EQUIPMENTS,LITERACY,POPULATION,NUMBER OF INCIDENTS,GROWTH IN GDP,INFLATION,TERRORIST GROUP
0,1993 blasts: Sanjay Dutt guilty under Arms Act...,2006-11-28 00:00:00,NOVEMBER,2006,---,---,---,No,0,---,DATA NOT AVAILABE,DATA NOT AVAILABLE,167,9.3%,6.7%,DATA NOT AVAILABLE
1,Over 300 Stone Pelting Incidents in Kashmir Si...,2019-10-10 00:00:00,OCTOBER,2019,---,Kashmir,North,No,0,STONE,68.74,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE
2,\r\r\n\r\r\n\r\r\n.---,2007-10-22 00:00:00,OCTOBER,2007,---,---,---,No,0,---,DATA NOT AVAILABE,DATA NOT AVAILABLE,149,9.8%,6.2%,DATA NOT AVAILABLE
3,At Least 100 Dead in India Terror Attacks.\r\r...,2008-11-26 00:00:00,NOVEMBER,2008,---,---,---,No,0,---,DATA NOT AVAILABE,DATA NOT AVAILABLE,534,3.9%,9.1%,DATA NOT AVAILABLE
4,\r\r\nTwo killed in first gun battle sine Kash...,2019-08-21 00:00:00,AUGUST,2019,---,Kashmir,North,Yes,2,---,68.74,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE
5,15 Indian commandos driver killed in Maoist at...,2020-01-07 00:00:00,JANUARY,2020,---,---,---,Yes,15,---,DATA NOT AVAILABE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,Maoist Communist Centre
6,\r\r\n DAWN.COM\r\r\n ...,2019-02-14 00:00:00,FEBRUARY,2019,---,---,---,No,0,---,DATA NOT AVAILABE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE
7,Maoist rebels kill 15 police commandos driver ...,2019-05-01 00:00:00,MAY,2019,---,---,---,No,0,---,DATA NOT AVAILABE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,Maoist Communist Centre
8,J&K; police seize truck smuggling 6 automatic ...,2019-09-12 00:00:00,SEPTEMBER,2019,---,Kashmir,North,No,0,RIFLES,68.74,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE
9,\r\r\nAttack by militants kills at least seven...,2017-07-10 00:00:00,JULY,2017,---,Kashmir,North,Yes,7,---,68.74,DATA NOT AVAILABLE,1000,7.2%,3.6%,DATA NOT AVAILABLE
10,Seven Hindu pilgrims killed in militant attack...,2017-07-10 00:00:00,JULY,2017,---,Kashmir,North,Yes,7,---,68.74,DATA NOT AVAILABLE,1000,7.2%,3.6%,DATA NOT AVAILABLE
11,Dozens Die in Bomb Attacks in Northeast India....,2008-10-30 00:00:00,OCTOBER,2008,---,---,---,No,0,BOMB,DATA NOT AVAILABE,DATA NOT AVAILABLE,534,3.9%,9.1%,DATA NOT AVAILABLE
12,Five stabbed at New York rabbi's home in 'terr...,2019-12-29 00:00:00,DECEMBER,2019,---,---,---,No,0,---,DATA NOT AVAILABE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE
13,6 Jammu and Kashmir deaths tied to security fo...,2020-01-01 00:00:00,JANUARY,2020,Jammu,Jammu and Kashmir,North,No,0,---,68.74,1526406,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE
14,Death toll rises to 14 in India clashes over n...,2019-12-20 00:00:00,DECEMBER,2019,---,---,---,Yes,14,---,DATA NOT AVAILABE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE
15,Death toll rises to 14 in India clashes over n...,2019-09-04 00:00:00,SEPTEMBER,2019,---,---,---,Yes,14,---,DATA NOT AVAILABE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE
16,\r\r\nFive killed in Kashmir's deadliest day s...,2019-10-17 00:00:00,OCTOBER,2019,---,---,---,Yes,5,---,DATA NOT AVAILABE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE
17,India protester shot in head driving outrage a...,2020-01-01 00:00:00,JANUARY,2020,---,---,---,No,0,---,DATA NOT AVAILABE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE
18,Two soldiers killed in overnight J&K encounter...,2020-01-01 00:00:00,JANUARY,2020,---,---,---,Yes,2,---,DATA NOT AVAILABE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE
19,Girl kills self over Facebook harassment.Top S...,2014-06-26 00:00:00,JUNE,2014,---,---,---,No,0,---,DATA NOT AVAILABE,DATA NOT AVAILABLE,860,7.4%,5.8%,DATA NOT AVAILABLE
20,.Ministry of External Affairs,2019-02-14 00:00:00,FEBRUARY,2019,---,---,---,No,0,---,DATA NOT AVAILABE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE
21,Indiaâ€™s ancient engineering marvel.Accessibili...,2017-01-17 00:00:00,JANUARY,2017,---,---,---,No,0,---,DATA NOT AVAILABE,DATA NOT AVAILABLE,1000,7.2%,3.6%,DATA NOT AVAILABLE
22,Water pollution is killing millions of Indians...,2019-10-04 00:00:00,OCTOBER,2019,---,---,---,No,0,---,DATA NOT AVAILABE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE
23,Assam businessman killed in Howrah.Top Searches:,2020-01-01 00:00:00,JANUARY,2020,---,Assam,North East,No,0,---,73.18,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE
24,Citizenship Act stir: Delhi Imams join student...,2019-12-18 00:00:00,DECEMBER,2019,---,Delhi,North,No,0,---,86.34,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE
25,Silent protest against NRC and Citizenship Ame...,2019-12-08 00:00:00,DECEMBER,2019,---,---,---,No,0,---,DATA NOT AVAILABE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE
26,Police fire tear gas as Delhi protesters decry...,2019-12-15 00:00:00,DECEMBER,2019,---,Assam,North East,No,0,---,73.18,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE
27,\r\r\n Maoist rebels kill 5 policem...,2019-06-15 00:00:00,JUNE,2019,---,---,---,No,0,---,DATA NOT AVAILABE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,Maoist Communist Centre
28,Kashmir attack: Bomb kills 40 Indian paramilit...,2019-02-14 00:00:00,FEBRUARY,2019,---,Kashmir,North,Yes,40,BOMB,68.74,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE
29,AT LEAST 200 KILLED IN INDIA AS MUSLIM-HINDU R...,1992-12-08 00:00:00,DECEMBER,1992,---,---,---,No,0,---,DATA NOT AVAILABE,DATA NOT AVAILABLE,237,5.5%,9.9%,DATA NOT AVAILABLE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,Our orbiter located Vikram lander first: Isro ...,2019-12-04 00:00:00,DECEMBER,2019,---,---,---,No,0,---,DATA NOT AVAILABE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE
71,Myanmar major contributor of smuggled gold to ...,2019-07-05 00:00:00,JULY,2019,---,---,---,No,0,---,DATA NOT AVAILABE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE
72,Illegal cross-border drug smuggling on the ris...,2019-08-20 00:00:00,AUGUST,2019,---,---,---,No,0,---,DATA NOT AVAILABE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE
73,Mehbooba Mufti's convoy pelted with stones in ...,2019-04-15 00:00:00,APRIL,2019,Anantnag,Jammu and Kashmir,North,No,0,STONES,68.74,1070144,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE
74,Kashmir: India tourist killed by stone throwin...,2018-05-08 00:00:00,MAY,2018,---,Kashmir,North,No,0,STONE,68.74,DATA NOT AVAILABLE,748,7.1%,3.5%,DATA NOT AVAILABLE
75,Stone pelter in Kashmir mauled by dogs? No itâ€™...,2019-05-30 00:00:00,MAY,2019,---,Kashmir,North,No,0,STONE,68.74,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE
76,Pakistan Runs Out of Options as India Tightens...,2019-08-09 00:00:00,AUGUST,2019,---,---,---,No,0,---,DATA NOT AVAILABE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE
77,The year India reset rules of engagement with ...,2019-12-31 00:00:00,DECEMBER,2019,---,---,---,No,0,---,DATA NOT AVAILABE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE
78,4 killed in Indian election violence as voting...,2019-04-11 00:00:00,APRIL,2019,---,---,---,Yes,4,---,DATA NOT AVAILABE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE
79,10 biggest national security failures.Security...,2008-12-19 00:00:00,DECEMBER,2008,Amritsar,Punjab,North,No,0,---,76.68,2490891,534,3.9%,9.1%,DATA NOT AVAILABLE
80,\r\r\r\n\t\t\t\t\t \t\t\t\t\t India concerned ...,2019-11-02 00:00:00,NOVEMBER,2019,Srinagar,Jammu and Kashmir,North,No,0,---,68.74,1269751,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE
81,\r\r\nInside India's hidden war\r\r\n.\r\r\nMo...,2019-05-09 00:00:00,MAY,2019,---,---,---,No,0,---,DATA NOT AVAILABE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE
82,35 Leaders with Criminal Records 78 Re-nominat...,2019-03-22 00:00:00,MARCH,2019,---,---,---,No,0,---,DATA NOT AVAILABE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE
83,CAA-NRC: Indian Muslims have broken the spell....,2020-01-02 00:00:00,JANUARY,2020,---,---,---,No,0,---,DATA NOT AVAILABE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE
84,Delhi won't extend odd-even scheme Arvind Kejr...,2019-11-18 00:00:00,NOVEMBER,2019,---,Delhi,North,No,0,---,86.34,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE
85,Will hefty traffic fines improve road safety?.---,2019-09-18 00:00:00,SEPTEMBER,2019,---,---,---,No,0,---,DATA NOT AVAILABE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE
86,This is how India can become the next Silicon ...,2019-10-02 00:00:00,OCTOBER,2019,---,---,---,No,0,---,DATA NOT AVAILABE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE
87,20 killed in terror attacks in J&K; since abro...,2019-11-27 00:00:00,NOVEMBER,2019,Jammu,Jammu and Kashmir,North,Yes,20,---,68.74,1526406,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE
88,FIR against ABVP NSUI members in Ahmedabad cla...,2020-01-08 00:00:00,JANUARY,2020,Ahmedabad,Gujarat,---,No,0,---,79.31,7208200,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE
89,Terrorist killed in encounter in J&K;'s Pulwam...,2020-01-07 00:00:00,JANUARY,2020,Jammu,Jammu and Kashmir,North,No,0,---,68.74,1526406,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE
90,Massive fire in Mumbai building eight injured....,2020-01-06 00:00:00,JANUARY,2020,---,---,---,Yes,8,---,DATA NOT AVAILABE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE
91,Roadies Revolution: Virat Kohli's doppelganger...,2020-01-08 00:00:00,JANUARY,2020,---,---,---,No,0,---,DATA NOT AVAILABE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE
92,From Pondicherry to Oxford campuses witness pr...,2020-01-06 00:00:00,JANUARY,2020,Pondicherry,Puducherry,South,No,0,---,86.55,950289,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE
93,Armed masked mob attacks JNU students leaves 2...,2020-01-06 00:00:00,JANUARY,2020,---,---,---,Yes,20,---,DATA NOT AVAILABE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE
94,A Kerala scientist's Arctic quest: nosy bears ...,2019-11-21 00:00:00,NOVEMBER,2019,Thiruvananthapuram,Kerala,South,No,0,---,93.91,3307284,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE
95,Man preparing for father's cremation killed in...,2019-12-22 00:00:00,DECEMBER,2019,---,---,---,No,0,---,DATA NOT AVAILABE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE
96,Delhi: 3 children among 9 dead in Kirari fire ...,2019-12-23 00:00:00,DECEMBER,2019,---,Delhi,North,Yes,3,---,86.34,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE
97,Gujarat: 3 killed as wall collapses on them du...,2019-12-22 00:00:00,DECEMBER,2019,---,Gujarat,---,Yes,3,---,79.31,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE
98,Two of family killed three hurt in car crash o...,2019-12-30 00:00:00,DECEMBER,2019,---,---,---,Yes,1,---,DATA NOT AVAILABE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE
99,5 kids from Ghaziabad family dead in room fire...,2019-12-31 00:00:00,DECEMBER,2019,Ghaziabad,Uttar Pradesh,Central,Yes,5,---,69.72,4661452,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE,DATA NOT AVAILABLE

# <center>END</center>